### PR TITLE
CI Integration and Arduino/PlatformIO description files

### PR DESCRIPTION
**Pull request by davidgraeff**
This merge request is splitted in 6 commits.
1. To make this library compatible with the Arduino/PlatformIO library managers, all source code need to be in a src subdirectory. This is also a good separation of source files and additional files.
2. Add extern "C" to coap.h so that it can be used in c++ code.
3. Add Arduino and PlatformIO library description files (json/ini formated files in the root of the repo)
4. Travis configuration file for continous integration. A simple arduino application is added to test/ which is build for arduino and plattformio. Gtest is used to perform actuall unit tests, but so far there is only a simple build+socket creation test added, but it is easy to expand the test coverage now.
5. Add travis ci status badge to the readme. 
6. Resolve name clash. You have defined an "assert" macro, but that already exists in the assert.h system header file. I renamed all coap asserts.

For continous integration with travis to work, you have to add the travis service in the preferences of this repository :)

I very much like this library, it would be great if it is added to the platformio.org and arduino library manager.

### CODE REVIEW

**Comment by Lobaro** [comment]
Thank you, will integrate it / test it asap and post the status here. Ardruino support is nice and should be no problem since the "round" nature of the library.

Greetings Tobi

**Comment by Niondir** [comment]
The changes are great and I try to apply them. I rebased your changes onto the current master and now the tests fail. 

Some major changes are:
- `CoAP_Init` signature changed
- `ifID` got removed and we only use a `SocketHandle_t`

I'm not able to run the tests locally. I wish you could provide some help to fix the tests and maybe provide some manual how to run at least the `basic_tests.cpp` locally.

The rebased code with some efforts to fix the tests is on branch `davidgraeff-rebased`.

Any help to fix the tests is welcome.

**Comment by davidgraeff** [comment]
I'm travelling the world and I'm in New Zealand at the moment, so can't really adapt the pull request in the near future unfortunately.

**Comment by Niondir** [comment]
Okay since just the CI build is not working I might just disable the tests for now and rely on the build. There will be a chance that Arduino builds break in future until that gets fixed again.

**Comment by Niondir** [comment]
Until I know how to move this Pull Request to another branch I just create a new Pull Request for branch davidgraeff-rebased

**Comment by Niondir** [comment]
Merged in https://github.com/Lobaro/lobaro-coap/pull/5

**Pull request closed without merging**
